/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.contratoControle;
import Controle.provaDeVidaControle;
import Modelo.DadosFinanceirosModelo;
import Modelo.provaDeVida;
import java.awt.CardLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Step_PV extends javax.swing.JFrame {

    /**
     * Creates new form Step_PV
     */
    public Step_PV() {
        initComponents();
        nextStep.setEnabled(false);
    }
    
    public void recolha(String nome, String bi, String genero, String naturalidade, String nasc, String telefone)
    {
        txtnome.setText(nome);
        txtbi.setText(bi);
        txtgenero.setText(genero);
        txtnaturalidade.setText(naturalidade);
        txtNascimento.setText(nasc);
        txtTelefone.setText(telefone);
        DadosFinanceiros df = new DadosFinanceiros();
        df.buscaDados(nome, bi, genero, naturalidade, nasc, telefone);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtnaturalidade = new javax.swing.JLabel();
        txtnome = new javax.swing.JLabel();
        txtbi = new javax.swing.JLabel();
        txtgenero = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nextStep = new javax.swing.JButton();
        OpSelected = new javax.swing.JComboBox<>();
        txtnome1 = new javax.swing.JLabel();
        panelGeral = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        carta = new javax.swing.JPanel();
        txtnome2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtnome15 = new javax.swing.JLabel();
        NcompletoCarta = new javax.swing.JTextField();
        txtnome16 = new javax.swing.JLabel();
        BICarta = new javax.swing.JTextField();
        txtnome17 = new javax.swing.JLabel();
        dataEmissaoCarta = new com.toedter.calendar.JDateChooser();
        txtnome18 = new javax.swing.JLabel();
        dataExpiraCarta = new com.toedter.calendar.JDateChooser();
        salvarCarta = new javax.swing.JButton();
        limparcarta = new javax.swing.JButton();
        BI = new javax.swing.JPanel();
        txtnome3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        BI0 = new javax.swing.JTextField();
        nomeCoBI = new javax.swing.JTextField();
        txtnome5 = new javax.swing.JLabel();
        txtnome6 = new javax.swing.JLabel();
        dataEmissao = new com.toedter.calendar.JDateChooser();
        txtnome7 = new javax.swing.JLabel();
        dataExpira = new com.toedter.calendar.JDateChooser();
        txtnome8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        passaporte = new javax.swing.JPanel();
        txtnome4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        txtnome10 = new javax.swing.JLabel();
        textNomeCompleto = new javax.swing.JTextField();
        txtnome11 = new javax.swing.JLabel();
        textBI = new javax.swing.JTextField();
        txtnome12 = new javax.swing.JLabel();
        dataEmissao1 = new com.toedter.calendar.JDateChooser();
        txtnome13 = new javax.swing.JLabel();
        dataExpira1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROVA DE VIDA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROVA DE VIDA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtnaturalidade.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtnaturalidade.setForeground(new java.awt.Color(0, 102, 153));
        txtnaturalidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtnaturalidade.setText("Naturalidade");

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtnome.setForeground(new java.awt.Color(0, 102, 153));
        txtnome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtnome.setText("Nome");

        txtbi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtbi.setForeground(new java.awt.Color(0, 102, 153));
        txtbi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbi.setText("BI");

        txtgenero.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtgenero.setForeground(new java.awt.Color(0, 102, 153));
        txtgenero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtgenero.setText("Genero");

        txtTelefone.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(0, 102, 153));
        txtTelefone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTelefone.setText("Telefone");

        txtNascimento.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtNascimento.setForeground(new java.awt.Color(0, 102, 153));
        txtNascimento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNascimento.setText("Data de Nascimento");

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-head-profile-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbi, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtnome)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtbi))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtgenero))
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnaturalidade))
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNascimento)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefone)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DADOS DO UTENTE ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        nextStep.setBackground(new java.awt.Color(0, 102, 153));
        nextStep.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        nextStep.setForeground(new java.awt.Color(255, 255, 255));
        nextStep.setText(" AVANÇAR »");
        nextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextStepActionPerformed(evt);
            }
        });

        OpSelected.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        OpSelected.setForeground(new java.awt.Color(0, 102, 153));
        OpSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opções", "Cartão de Condução", "BI Atualizado", "Passaporte" }));
        OpSelected.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OpSelectedItemStateChanged(evt);
            }
        });
        OpSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpSelectedActionPerformed(evt);
            }
        });

        txtnome1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtnome1.setForeground(new java.awt.Color(0, 102, 153));
        txtnome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome1.setText("Tipo de Documento");

        panelGeral.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        panelGeral.add(jPanel5, "card2");

        carta.setBackground(new java.awt.Color(204, 204, 255));
        carta.setName("carta"); // NOI18N

        txtnome2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtnome2.setForeground(new java.awt.Color(255, 255, 255));
        txtnome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome2.setText("DADOS DA CARTA DE CONDUNÇÃO");

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        txtnome15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome15.setForeground(new java.awt.Color(255, 255, 255));
        txtnome15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome15.setText("Nome Completo");

        txtnome16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome16.setForeground(new java.awt.Color(255, 255, 255));
        txtnome16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome16.setText("ID da Carta");

        txtnome17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome17.setForeground(new java.awt.Color(255, 255, 255));
        txtnome17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome17.setText("Data de Emissão");

        txtnome18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome18.setForeground(new java.awt.Color(255, 255, 255));
        txtnome18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome18.setText("Data de Experiração");

        salvarCarta.setBackground(new java.awt.Color(255, 255, 255));
        salvarCarta.setForeground(new java.awt.Color(0, 102, 153));
        salvarCarta.setText("Salvar");
        salvarCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCartaActionPerformed(evt);
            }
        });

        limparcarta.setBackground(new java.awt.Color(255, 255, 255));
        limparcarta.setForeground(new java.awt.Color(0, 102, 153));
        limparcarta.setText("Limpar");
        limparcarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparcartaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cartaLayout = new javax.swing.GroupLayout(carta);
        carta.setLayout(cartaLayout);
        cartaLayout.setHorizontalGroup(
            cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaLayout.createSequentialGroup()
                .addGroup(cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartaLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(txtnome2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartaLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartaLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cartaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnome16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NcompletoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnome17, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(BICarta, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dataEmissaoCarta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(cartaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnome18, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(cartaLayout.createSequentialGroup()
                                            .addComponent(salvarCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(limparcarta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(dataExpiraCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        cartaLayout.setVerticalGroup(
            cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtnome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtnome15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NcompletoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtnome16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BICarta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtnome17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(dataEmissaoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(txtnome18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataExpiraCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(cartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparcarta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        panelGeral.add(carta, "carta");

        BI.setBackground(new java.awt.Color(204, 204, 204));

        txtnome3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtnome3.setForeground(new java.awt.Color(255, 255, 255));
        txtnome3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome3.setText("DADOS DO BI");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        txtnome5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome5.setForeground(new java.awt.Color(255, 255, 255));
        txtnome5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome5.setText("Data de Experiração");

        txtnome6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome6.setForeground(new java.awt.Color(255, 255, 255));
        txtnome6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome6.setText("Nome Completo");

        txtnome7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome7.setForeground(new java.awt.Color(255, 255, 255));
        txtnome7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome7.setText("BI nº");

        txtnome8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome8.setForeground(new java.awt.Color(255, 255, 255));
        txtnome8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome8.setText("Data de Emissão");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 102, 153));
        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BILayout = new javax.swing.GroupLayout(BI);
        BI.setLayout(BILayout);
        BILayout.setHorizontalGroup(
            BILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BILayout.createSequentialGroup()
                .addGroup(BILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BILayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(BILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BILayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BILayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(BILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCoBI, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BILayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtnome7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dataEmissao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BI0, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dataExpira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BILayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtnome6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BILayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtnome8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BILayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(txtnome5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        BILayout.setVerticalGroup(
            BILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BILayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtnome3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(txtnome6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeCoBI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(txtnome7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BI0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtnome8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(txtnome5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataExpira, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(BILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        panelGeral.add(BI, "bi");

        passaporte.setBackground(new java.awt.Color(255, 255, 255));

        txtnome4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtnome4.setForeground(new java.awt.Color(0, 102, 153));
        txtnome4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome4.setText("DADOS DO PASSAPORTE");

        jPanel13.setBackground(new java.awt.Color(0, 102, 153));
        jPanel13.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        txtnome10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome10.setForeground(new java.awt.Color(0, 102, 153));
        txtnome10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome10.setText("Passaporte ID");

        txtnome11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome11.setForeground(new java.awt.Color(0, 102, 153));
        txtnome11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome11.setText("Nome Completo");

        txtnome12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome12.setForeground(new java.awt.Color(0, 102, 153));
        txtnome12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome12.setText("Data de Emissão");

        txtnome13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtnome13.setForeground(new java.awt.Color(0, 102, 153));
        txtnome13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnome13.setText("Data de Experiração");

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 153));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passaporteLayout = new javax.swing.GroupLayout(passaporte);
        passaporte.setLayout(passaporteLayout);
        passaporteLayout.setHorizontalGroup(
            passaporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passaporteLayout.createSequentialGroup()
                .addGroup(passaporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passaporteLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(passaporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(passaporteLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtnome4, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(passaporteLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(passaporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(passaporteLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtnome11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNomeCompleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(textBI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(dataEmissao1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnome10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnome12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnome13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataExpira1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        passaporteLayout.setVerticalGroup(
            passaporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passaporteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtnome4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(txtnome11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtnome10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBI, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txtnome12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataEmissao1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(txtnome13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataExpira1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(passaporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        panelGeral.add(passaporte, "passaporte");

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("reinicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OpSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnome1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txtnome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OpSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addComponent(nextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpSelectedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OpSelectedItemStateChanged
        // TODO add your handling code here:
        String OpSelect = OpSelected.getSelectedItem().toString();
        if(OpSelect.equals("Cartão de Condução"))
        {
            CardLayout cl = (CardLayout) panelGeral.getLayout();
            cl.show(panelGeral , "carta");
        }
        
        else if(OpSelect.equals("BI Atualizado"))
        {
            CardLayout cl = (CardLayout) panelGeral.getLayout();
            cl.show(panelGeral , "bi");
        }
        
        else if(OpSelect.equals("Passaporte"))
        {
            CardLayout cl = (CardLayout) panelGeral.getLayout();
            cl.show(panelGeral , "passaporte");
        }
        
        else{
            CardLayout cl = (CardLayout) panelGeral.getLayout();
            cl.show(panelGeral , "card2");
        }
    }//GEN-LAST:event_OpSelectedItemStateChanged

    private void limparcartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparcartaActionPerformed
        // TODO add your handling code here:
        NcompletoCarta.setText("");
        BICarta.setText("");
        dataEmissaoCarta.setDate(null);
        dataExpiraCarta.setDate(null);
    }//GEN-LAST:event_limparcartaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        nomeCoBI.setText("");
        BI0.setText("");
        dataEmissao.setDate(null);
        dataExpira.setDate(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       textNomeCompleto.setText("");
       textBI.setText("");
       dataEmissao1.setDate(null);
       dataExpira1.setDate(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void salvarCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCartaActionPerformed
        // TODO add your handling code here:
        if((NcompletoCarta.getText().equals(""))||(BICarta.getText().equals("")))
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos");
        }

        else if(dataEmissaoCarta.getDate() == null||dataExpiraCarta.getDate() == null)
        {
             JOptionPane.showMessageDialog(null, "datas Invalidas!");
        }
        
        else{
            if(!"BI".equals(txtbi.getText()))
            {
                
            String NomeCompleto = NcompletoCarta.getText();
            String OBI = BICarta.getText();
            SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
            String dataEmissao = ft.format(dataEmissaoCarta.getDate());
            String dataExpirar = ft.format(dataExpiraCarta.getDate());
            salvarCarta.setEnabled(false);
            OpSelected.setEnabled(false);
            limparcarta.setEnabled(false);
            JOptionPane.showMessageDialog(null, "DADOS ADICIONADOS COM SUCESSO, PODE AVANÇAR");
        nextStep.setEnabled(true);
                provaDeVida pv = new provaDeVida(NomeCompleto, OBI, dataEmissao, dataExpirar, txtbi.getText());
                 try {
                BufferedWriter conexao = new BufferedWriter(new FileWriter("provas_de_vida.txt", true));
                provaDeVidaControle pvc = new provaDeVidaControle();
                pvc.Salvar(conexao, pv);
                    } catch (IOException ex) {
                        Logger.getLogger(DadosFinanceiros.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
            }
            
            else{            
                JOptionPane.showMessageDialog(null, "Sem Utente Selecionado");
            }
        }
    }//GEN-LAST:event_salvarCartaActionPerformed

    private void nextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextStepActionPerformed
        // TODO add your handling code here:
        DadosFinanceiros df = new DadosFinanceiros();
        String nome = txtnome.getText();
        String bi = txtbi.getText();
        String genero = txtgenero.getText();
        String naturalidade = txtnaturalidade.getText();
        String nasc = txtNascimento.getText();
        String telefone = txtTelefone.getText();
        df.buscaDados(nome, bi, genero, naturalidade, nasc, telefone);
        this.dispose();
        df.setVisible(true);
        
    }//GEN-LAST:event_nextStepActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(nomeCoBI.getText().equals("") || BI0.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Preencha os campos vazios.");
        }
        
        else if(dataExpira.getDate() == null || dataEmissao.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "datas inavalidas.");
        }
        
        else{
            if(!"BI".equals(txtbi.getText()))
            {
                
            String NomeCompleto = nomeCoBI.getText();
            String OBI = BI0.getText();
            SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
            String dataEmissa = ft.format(dataEmissao.getDate());
            String dataExpirar = ft.format(dataExpira.getDate());
            salvarCarta.setEnabled(false);
            OpSelected.setEnabled(false);
            limparcarta.setEnabled(false);
            JOptionPane.showMessageDialog(null, "DADOS ADICIONADOS COM SUCESSO, PODE AVANÇAR");
        nextStep.setEnabled(true);
         provaDeVida pv = new provaDeVida(NomeCompleto, OBI, dataEmissa, dataExpirar, txtbi.getText());
                 try {
                BufferedWriter conexao = new BufferedWriter(new FileWriter("provas_de_vida.txt", true));
                provaDeVidaControle pvc = new provaDeVidaControle();
                pvc.Salvar(conexao, pv);
                    } catch (IOException ex) {
                        Logger.getLogger(DadosFinanceiros.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
            
            else{            
                JOptionPane.showMessageDialog(null, "Sem Utente Selecionado");
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(textNomeCompleto.getText().equals("") || textBI.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Preencha os campos vazios");
        }
        
        else if(dataExpira1.getDate() == null || dataEmissao1.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Datas invalidas");
        }
        
        else{
            
            if(!"BI".equals(txtbi.getText()))
            {
                
            String NomeCompleto = textNomeCompleto.getText();
            String OBI = textBI.getText();
            SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
            String dataEmissao = sdf1.format(dataEmissao1.getDate());
            String dataExpirar = sdf1.format(dataExpira1.getDate());
            JOptionPane.showMessageDialog(null, "DADOS ADICIONADOS COM SUCESSO, PODE AVANÇAR");
        nextStep.setEnabled(true);
         provaDeVida pv = new provaDeVida(NomeCompleto, OBI, dataEmissao, dataExpirar, txtbi.getText());
                 try {
                BufferedWriter conexao = new BufferedWriter(new FileWriter("provas_de_vida.txt", true));
                provaDeVidaControle pvc = new provaDeVidaControle();
                pvc.Salvar(conexao, pv);
                    } catch (IOException ex) {
                        Logger.getLogger(DadosFinanceiros.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
            
            else{            
                JOptionPane.showMessageDialog(null, "Sem Utente Selecionado");
            }
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void OpSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Step_PV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Step_PV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Step_PV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Step_PV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Step_PV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BI;
    private javax.swing.JTextField BI0;
    private javax.swing.JTextField BICarta;
    private javax.swing.JTextField NcompletoCarta;
    private javax.swing.JComboBox<String> OpSelected;
    private javax.swing.JPanel carta;
    private com.toedter.calendar.JDateChooser dataEmissao;
    private com.toedter.calendar.JDateChooser dataEmissao1;
    private com.toedter.calendar.JDateChooser dataEmissaoCarta;
    private com.toedter.calendar.JDateChooser dataExpira;
    private com.toedter.calendar.JDateChooser dataExpira1;
    private com.toedter.calendar.JDateChooser dataExpiraCarta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton limparcarta;
    private javax.swing.JButton nextStep;
    private javax.swing.JTextField nomeCoBI;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JPanel passaporte;
    private javax.swing.JButton salvarCarta;
    private javax.swing.JTextField textBI;
    private javax.swing.JTextField textNomeCompleto;
    private javax.swing.JLabel txtNascimento;
    private javax.swing.JLabel txtTelefone;
    private javax.swing.JLabel txtbi;
    private javax.swing.JLabel txtgenero;
    private javax.swing.JLabel txtnaturalidade;
    private javax.swing.JLabel txtnome;
    private javax.swing.JLabel txtnome1;
    private javax.swing.JLabel txtnome10;
    private javax.swing.JLabel txtnome11;
    private javax.swing.JLabel txtnome12;
    private javax.swing.JLabel txtnome13;
    private javax.swing.JLabel txtnome15;
    private javax.swing.JLabel txtnome16;
    private javax.swing.JLabel txtnome17;
    private javax.swing.JLabel txtnome18;
    private javax.swing.JLabel txtnome2;
    private javax.swing.JLabel txtnome3;
    private javax.swing.JLabel txtnome4;
    private javax.swing.JLabel txtnome5;
    private javax.swing.JLabel txtnome6;
    private javax.swing.JLabel txtnome7;
    private javax.swing.JLabel txtnome8;
    // End of variables declaration//GEN-END:variables

    private void pv(String NomeCompleto, String OBI, String dataEmissao, String dataExpirar) {
       }
}
